root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # "." tells Go to build the package in the current directory
  cmd = "go build -o ./tmp/main ."
  # This matches the output path defined in the 'cmd' line above
  bin = "tmp/main"
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  include_dir = []
  exclude_file = []
  delay = 1000
  stop_on_error = true
  log = "build-errors.log"

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true